### ISSUE TITLE
key Error

### ISSUE THREAD

**Issue by xiaolinyezi** [aliyun/DCT-Mask#7]
detectron 0.1.3---your repo
pytorch 1.8.0
CUDA 11.1
'Non-existent config key: MODEL.ROI_MASK_HEAD.DCT_VECTOR_DIM

**Comment by xiaolinyezi** [comment]
find the error, fixed

**Comment by llyyyll** [comment]
> find the error, fixed

I had the same error, can you tell me how it was solved
